/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Neto
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    private java.util.List<Time> classificacaoFinal;
    
    public MainWindow(java.util.List<Time> classificacao) {
    this.classificacaoFinal = classificacao; 
    initComponents();                        
    preencherTabela();                       
}
    /**
 * Este método preenche a JTable com os dados da classificação.
 */
private void preencherTabela() {
    // Define os nomes que aparecerão no cabeçalho das colunas
    String[] colunas = {"Pos", "Time", "Pts", "J", "V", "E", "D", "GP", "GC", "SG"};

    // Cria um "modelo" para a tabela, que é onde os dados realmente ficam
    javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(colunas, 0);

    int posicao = 1;
    // Percorre a lista de times e adiciona cada um como uma nova linha no modelo
    for (Time time : this.classificacaoFinal) {
        Object[] linha = {
            posicao,
            time.getNome(),
            time.getPontos(),
            time.getJogosDisputados(),
            time.getVitorias(),
            time.getEmpates(),
            time.getDerrotas(),
            time.getGolsPro(),
            time.getGolsContra(),
            time.getSaldoGols()
        };
        tableModel.addRow(linha);
        posicao++;
    }

    // Associa o modelo (agora cheio de dados) à nossa JTable visual
    // O nome "tabelaClassificacao" aqui deve ser o mesmo da sua variável cinza
    tabelaClassificacao.setModel(tableModel);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaClassificacao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dados do Brasileirao");

        tabelaClassificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaClassificacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaClassificacao;
    // End of variables declaration//GEN-END:variables
}
